defaults: &defaults
  admin_secret_path: "corp"
  host_name: "htt://www.devox.cc"
  recaptcha:
    site_key: "6Le0ak0UAAAAAJhuMHrsVrZWEpe1AShWkRypn44x"
    secret_key: "6Le0ak0UAAAAAO5g7I87IoBgMhDZvVW-uBawxXJk"
  action_mailer:
    default_url_options:
      host: "www.devox.cc"
    delivery_method: :smtp
    smtp_settings:
      address: "smtp.mailgun.org"
      port: 587
      domain: "mail.devox.cc"
      user_name: "postmaster@mail.devox.cc"
      password: "4fe673e8ad67b373a18c7edb09d55aeb-db1f97ba-074895f2"
      authentication: :plain
      enable_starttls_auto: true

production:
  <<: *defaults

development:
  <<: *defaults