defaults: &defaults
  admin_secret_path: "corp"
  host: "https://www.devox.cc"
  site_name: "devox"
  recaptcha:
    site_key: "6Le0ak0UAAAAAJhuMHrsVrZWEpe1AShWkRypn44x"
    secret_key: "6Le0ak0UAAAAAO5g7I87IoBgMhDZvVW-uBawxXJk"
  smtp_host: "devox.cc"
  smtp_domain: "mail.devox.cc"
  smtp_user_name: "postmaster@mail.devox.cc"
  smtp_password: "c8e2149244b411beead277c3270f1e64-116e1e4d-424cd137"
  

production:
  <<: *defaults

development:
  <<: *defaults