---
hq_zh:
  address: hq_address_zh
  number: hq_number_zh
  fax: hq_fax_zh
  email: hq_email_zh
hq_en:
  address: hq_address_en
  number: hq_number_en
  fax: hq_fax_en
  email: hq_email_en
north:
  name: north_name
  number: north_number
  email: north_email
central:
  name: central_name
  number: central_number
  email: central_email
south:
  name: south_name
  number: south_number
  email: south_email
