---
hq_zh:
  電話: 99-9999
  傳真: 00-0000000
  EMAIL: hq@mail.com
  地址: 成績日期的說韓國質量就在
hq_en:
  number: hq_number_en
  fax: hq_fax_en
  EMAIL: hq_email_en
  address: hq_address_en
北區:
  聯絡人: 開發顯 得基
  電話: 01-1111111
  EMAIL: north@mail.com
中區:
  聯絡人: 開發顯 得基
  電話: 01-1111111
  EMAIL: central@mail.com
南區:
  聯絡人: 開發顯 得基
  電話: 01-1111111
  EMAIL: south@mail.com
