---
tracking:
  FB_id: Kerr.Huang
  GA_id: ha
  GTM_id: yo
images:
  logo_zh-TW: "/images/system/logo_zh-TW.jpg"
  logo_en: "/images/system/logo_en.jpg"
site_name:
  zh-TW: site tw2
  en: EN sitename
